const NAV_ITEMS = ["Home", "Search", "Saved", "Profile"];
let nav = null;
let dot = null;
let activeIndex = 0;
let dragging = false;
let startX = 0;
let currentX = 0;
let moved = false;
let swipeStartX = 0;
let swipeStartY = 0;
let swipeTracking = false;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const buttons=()=>[...document.querySelectorAll(".bottom-nav .nav-item")];
const centers=()=>{if(!nav)return [];const track=nav.querySelector(".ximo-fluid-track");if(!track)return [];const tr=track.getBoundingClientRect();return buttons().slice(0,4).map(b=>{const r=b.getBoundingClientRect();return r.left+r.width/2-tr.left-6})};
const currentNavIndex=()=>{const bs=buttons();const active=bs.findIndex(b=>b.classList.contains("active"));return active>=0?clamp(active,0,3):activeIndex};
const updateIndicator=(index,animate=true)=>{activeIndex=clamp(index,0,3);if(!nav||!dot)return;const cs=centers();const x=cs[activeIndex]??0;dot.style.transition=animate?"transform .26s cubic-bezier(.2,.8,.2,1)":"none";dot.style.transform=`translateX(${x}px)`;document.body.dataset.ximoSection=NAV_ITEMS[activeIndex]};
const goTo=index=>{const target=buttons()[clamp(index,0,3)];if(!target)return;target.click();requestAnimationFrame(()=>updateIndicator(currentNavIndex()))};
const install=()=>{const next=document.querySelector(".bottom-nav");if(!next||next===nav)return;nav=next;nav.dataset.fluidReady="1";const track=document.createElement("span");track.className="ximo-fluid-track";const rail=document.createElement("span");rail.className="ximo-fluid-rail";dot=document.createElement("span");dot.className="ximo-fluid-dot";track.append(rail,dot);nav.prepend(track);
const onDown=e=>{if(e.target.closest(".create-button"))return;dragging=true;moved=false;startX=currentX=e.clientX;nav.classList.add("is-dragging");nav.setPointerCapture?.(e.pointerId)};
const onMove=e=>{if(!dragging)return;currentX=e.clientX;if(Math.abs(currentX-startX)>7)moved=true;if(!moved)return;const cs=centers();if(!cs.length)return;const base=cs[activeIndex]??0;const progress=clamp(activeIndex-(currentX-startX)/Math.max(100,nav.clientWidth/3),0,3);const lo=Math.floor(progress),hi=Math.min(3,lo+1),mix=progress-lo;const x=cs[lo]+((cs[hi]??cs[lo])-cs[lo])*mix;dot.style.transition="none";dot.style.transform=`translateX(${x}px)`};
const onUp=()=>{if(!dragging)return;dragging=false;nav.classList.remove("is-dragging");if(moved){const dx=currentX-startX;if(Math.abs(dx)>32)goTo(activeIndex+(dx<0?1:-1));else updateIndicator(activeIndex)}};
nav.addEventListener("pointerdown",onDown);nav.addEventListener("pointermove",onMove);nav.addEventListener("pointerup",onUp);nav.addEventListener("pointercancel",onUp);buttons().slice(0,4).forEach((b,i)=>b.addEventListener("click",()=>setTimeout(()=>updateIndicator(i),0)));updateIndicator(currentNavIndex(),false);};
const onPageDown=e=>{if(e.target.closest(".bottom-nav,.post-detail,.create-backdrop,.account-settings,#ximo-auth-root,input,textarea,select,button,a,.card"))return;swipeTracking=true;swipeStartX=e.clientX;swipeStartY=e.clientY};
const onPageUp=e=>{if(!swipeTracking)return;swipeTracking=false;const dx=e.clientX-swipeStartX,dy=e.clientY-swipeStartY;if(Math.abs(dx)<70||Math.abs(dx)<Math.abs(dy)*1.25)return;goTo(currentNavIndex()+(dx<0?1:-1))};
document.addEventListener("pointerdown",onPageDown,{passive:true});document.addEventListener("pointerup",onPageUp,{passive:true});
const boot=()=>install();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();new MutationObserver(install).observe(document.body,{childList:true});