import React, { useEffect, useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import "./style.css";
import "./profile.css";

const seedPosts = [
  {id:1,title:"Warm minimal living room",category:"Home",height:"tall",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",score:98},
  {id:2,title:"A cozy reading corner",category:"Cozy",height:"short",image:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85",score:91},
  {id:3,title:"Simple desk setup",category:"Workspace",height:"medium",image:"https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=900&q=85",score:95},
  {id:4,title:"Soft bedroom ideas",category:"Bedroom",height:"tall",image:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=85",score:94},
  {id:5,title:"Plants that change a room",category:"Plants",height:"medium",image:"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85",score:88},
  {id:6,title:"Clean kitchen inspiration",category:"Kitchen",height:"short",image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85",score:92}
];
const builtInCategories = ["Home","Cozy","Workspace","Bedroom","Plants","Kitchen"];
const categoryIcons = ["⌂","☁","▣","◒","✿","◇","✦","✧","○","△"];
const iconForCategory = (name,index=0)=>categoryIcons[Math.abs([...name].reduce((a,c)=>a+c.charCodeAt(0),index))%categoryIcons.length];
function readLocal(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}}

function App(){
 const [active,setActive]=useState("Home"),[view,setView]=useState("home"),[profileTab,setProfileTab]=useState("posts"),[query,setQuery]=useState("");
 const [recentSearches,setRecentSearches]=useState(()=>window.ximoSearch?.recent?.()||[]),[selectedPost,setSelectedPost]=useState(null),[saved,setSaved]=useState(()=>readLocal("ximo-saved",[]));
 const [userPosts,setUserPosts]=useState(()=>readLocal("ximo-posts",[])),[customCategories,setCustomCategories]=useState(()=>readLocal("ximo-custom-categories",[]));
 const [collections,setCollections]=useState(()=>readLocal("ximo-collections",[])),[showCreate,setShowCreate]=useState(false),[showCategories,setShowCategories]=useState(false),[editingCategory,setEditingCategory]=useState(null),[categoryName,setCategoryName]=useState("");
 const [collectionName,setCollectionName]=useState(""),[collectionDescription,setCollectionDescription]=useState(""),[showCollectionCreate,setShowCollectionCreate]=useState(false),[editingCollection,setEditingCollection]=useState(null),[selectedCollection,setSelectedCollection]=useState(null);
 const [title,setTitle]=useState(""),[category,setCategory]=useState("Home"),[image,setImage]=useState(""),[imageName,setImageName]=useState(""),[navHidden,setNavHidden]=useState(false),[feedMode,setFeedMode]=useState("for-you"),[feedCount,setFeedCount]=useState(1),[loading,setLoading]=useState(true),[toast,setToast]=useState("");
 useEffect(()=>localStorage.setItem("ximo-saved",JSON.stringify(saved)),[saved]);useEffect(()=>localStorage.setItem("ximo-posts",JSON.stringify(userPosts)),[userPosts]);useEffect(()=>localStorage.setItem("ximo-custom-categories",JSON.stringify(customCategories)),[customCategories]);useEffect(()=>localStorage.setItem("ximo-collections",JSON.stringify(collections)),[collections]);
 useEffect(()=>{const t=setTimeout(()=>setLoading(false),650);return()=>clearTimeout(t)},[]);useEffect(()=>{let lastY=window.scrollY;const onScroll=()=>{const y=window.scrollY;if(y>lastY+8&&y>100)setNavHidden(true);if(y<lastY-8)setNavHidden(false);lastY=y};window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
 useEffect(()=>{document.body.style.overflow=selectedPost||showCategories||showCreate||showCollectionCreate?"hidden":"";return()=>{document.body.style.overflow=""}},[selectedPost,showCategories,showCreate,showCollectionCreate]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(t)},[toast]);
 const categories=useMemo(()=>[...builtInCategories,...customCategories],[customCategories]);const posts=useMemo(()=>[...userPosts,...seedPosts],[userPosts]);
 useEffect(()=>{if(!categories.includes(category))setCategory(categories[0]||"Home")},[categories,category]);
 const filtered=useMemo(()=>posts.filter(p=>{const q=query.trim().toLowerCase();return(!q||`${p.title} ${p.category}`.toLowerCase().includes(q))&&(active==="Home"||active==="Saved"||active==="Search"||active==="Profile"||p.category===active)&&(active!=="Saved"||saved.includes(p.id))}),[posts,query,active,saved]);
 const forYou=useMemo(()=>[...posts].sort((a,b)=>((saved.includes(b.id)?20:0)+b.score)-((saved.includes(a.id)?20:0)+a.score)),[posts,saved]);const trending=useMemo(()=>[...posts].sort((a,b)=>b.score-a.score),[posts]);const fresh=useMemo(()=>[...posts].reverse(),[posts]);const modePosts=feedMode==="trending"?trending:feedMode==="fresh"?fresh:forYou;const shownFeed=modePosts.slice(0,feedCount*4);
 const rememberSearch=value=>{const next=window.ximoSearch?.remember?.(value)||recentSearches;setRecentSearches(next)};const clearRecentSearches=()=>{const next=window.ximoSearch?.clear?.()||[];setRecentSearches(next)};const removeRecentSearch=value=>{const next=window.ximoSearch?.remove?.(value)||recentSearches.filter(x=>x!==value);setRecentSearches(next)};
 const submitSearch=e=>{e?.preventDefault?.();const q=query.trim();if(!q)return;rememberSearch(q);setView("search");setActive("Search");setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};const useRecentSearch=value=>{setQuery(value);rememberSearch(value);setView("search");setActive("Search");setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};const goHome=()=>{setView("home");setActive("Home");setQuery("");setFeedMode("for-you");setFeedCount(1);setSelectedCollection(null);window.scrollTo({top:0,behavior:"smooth"})};const openSearch=()=>{setView("search");setActive("Search");setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"});setTimeout(()=>document.querySelector(".search-page-input")?.focus(),120)};const openSaved=()=>{setView("saved");setActive("Saved");setQuery("");setFeedCount(1);setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};const chooseCategory=item=>{setQuery("");setActive(item);setView("home");setFeedMode("for-you");setFeedCount(1);setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};const openProfile=()=>{setView("profile");setActive("Profile");setProfileTab("posts");setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};const openPost=p=>{setSelectedPost(p);setNavHidden(false)};
 const toggleSave=id=>{const willSave=!saved.includes(id);setSaved(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);setToast(willSave?"Saved to your Ximo ideas 🧡":"Removed from saved")};
 const sharePost=async p=>{const url=`${window.location.origin}${window.location.pathname}?post=${encodeURIComponent(p.id)}`;try{if(navigator.share){await navigator.share({title:`${p.title} — Ximo`,text:`Check out this idea on Ximo: ${p.title}`,url});setToast("Shared from Ximo 🧡");return}await navigator.clipboard.writeText(url);setToast("Post link copied 🧡")}catch(e){if(e?.name!=="AbortError"){try{await navigator.clipboard.writeText(url);setToast("Post link copied 🧡")}catch{setToast("Could not share this post")}}}};
 const handleImage=e=>{const file=e.target.files?.[0];if(!file||!file.type.startsWith("image/"))return;setImageName(file.name);const reader=new FileReader();reader.onload=()=>setImage(reader.result);reader.readAsDataURL(file)};
 const publish=e=>{e.preventDefault();if(!title.trim()||!image)return;setUserPosts(cur=>[{id:`local-${Date.now()}`,title:title.trim(),category,height:"medium",image,score:100},...cur]);setTitle("");setCategory(categories[0]||"Home");setImage("");setImageName("");setShowCreate(false);setToast("Your idea is live on Ximo 🧡");goHome()};const loadMore=()=>{if(shownFeed.length<modePosts.length){setFeedCount(c=>c+1);setToast("More ideas loaded")}};
 const openCategoryManager=()=>{setShowCategories(true);setEditingCategory(null);setCategoryName("");setNavHidden(false)};const saveCategory=()=>{const name=categoryName.trim().replace(/\s+/g," ");if(!name)return;if(name.length>28){setToast("Category names can be 28 characters max");return}const exists=[...builtInCategories,...customCategories].some(c=>c.toLowerCase()===name.toLowerCase()&&c!==editingCategory);if(exists){setToast("That category already exists");return}if(editingCategory){setCustomCategories(cur=>cur.map(c=>c===editingCategory?name:c));setUserPosts(cur=>cur.map(p=>p.category===editingCategory?{...p,category:name}:p));if(active===editingCategory)setActive(name);if(category===editingCategory)setCategory(name);setToast(`Renamed to ${name} 🧡`)}else{setCustomCategories(cur=>[...cur,name]);setCategory(name);setToast(`${name} created 🧡`)}setCategoryName("");setEditingCategory(null)};const startEditCategory=name=>{setEditingCategory(name);setCategoryName(name)};const deleteCategory=name=>{if(!window.confirm(`Delete “${name}”? Posts already using it will move to Home.`))return;setCustomCategories(cur=>cur.filter(c=>c!==name));setUserPosts(cur=>cur.map(p=>p.category===name?{...p,category:"Home"}:p));if(active===name)setActive("Home");if(category===name)setCategory("Home");setToast(`${name} deleted`)};
 const createCollection=()=>{const name=collectionName.trim().replace(/\s+/g," ");if(!name){setToast("Give your collection a name");return}if(name.length>36){setToast("Collection names can be 36 characters max");return}if(collections.some(c=>c.name.toLowerCase()===name.toLowerCase()&&c.id!==editingCollection)){setToast("That collection already exists");return}if(editingCollection){setCollections(cur=>cur.map(c=>c.id===editingCollection?{...c,name,description:collectionDescription.trim()}:c));setToast(`${name} updated 🧡`)}else{setCollections(cur=>[{id:`collection-${Date.now()}`,name,description:collectionDescription.trim(),postIds:[],createdAt:Date.now()},...cur]);setToast(`${name} created 🧡`)}setCollectionName("");setCollectionDescription("");setEditingCollection(null);setShowCollectionCreate(false)};
 const openCollection=id=>{setSelectedCollection(id);setView("collection");setActive("Saved");setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};const editCollection=c=>{setEditingCollection(c.id);setCollectionName(c.name);setCollectionDescription(c.description||"");setShowCollectionCreate(true)};const deleteCollection=id=>{const c=collections.find(x=>x.id===id);if(!c)return;if(!window.confirm(`Delete “${c.name}”? Your saved ideas will stay saved.`))return;setCollections(cur=>cur.filter(x=>x.id!==id));if(selectedCollection===id){setSelectedCollection(null);setView("saved")};setToast(`${c.name} deleted`)};const toggleCollectionPost=(collectionId,postId)=>{setCollections(cur=>cur.map(c=>c.id===collectionId?{...c,postIds:c.postIds.includes(postId)?c.postIds.filter(id=>id!==postId):[...c.postIds,postId]}:c));const c=collections.find(x=>x.id===collectionId);const adding=!c?.postIds.includes(postId);setToast(adding?`Added to ${c?.name||"collection"} 🧡`:`Removed from ${c?.name||"collection"}`)};
 const renderFeed=(items=filtered,mode="normal")=>items.length===0?<div className="empty-state"><div className="empty-icon">⌕</div><h2>{view==="saved"?"No saved ideas yet.":"No ideas found."}</h2><p>{view==="saved"?"Tap the heart on an idea to keep it here.":"Try a different search or explore another category."}</p><button onClick={view==="saved"?goHome:()=>{setQuery("");setActive("Search")}}>{view==="saved"?"Explore ideas":"Clear search"}</button></div>:<section className={`feed ${mode==="masonry"?"masonry-feed":""}`}>{items.map(p=><article className={`card ${p.height}`} key={p.id} onClick={()=>openPost(p)} tabIndex="0" onKeyDown={e=>e.key==="Enter"&&openPost(p)}><img src={p.image} alt={p.title} loading="lazy"/><div className="card-overlay"><div><span>{p.category}</span><h2>{p.title}</h2></div><button className={saved.includes(p.id)?"save saved":"save"} onClick={e=>{e.stopPropagation();toggleSave(p.id)}}>{saved.includes(p.id)?"♥":"♡"}</button></div></article>)}</section>;
 const savedPosts=posts.filter(p=>saved.includes(p.id));const profilePosts=userPosts;const relatedPosts=selectedPost?posts.filter(p=>p.id!==selectedPost.id&&p.category===selectedPost.category).slice(0,4):[];const feedTabs=[{id:"for-you",label:"For You",icon:"✦"},{id:"trending",label:"Trending",icon:"↗"},{id:"fresh",label:"Fresh",icon:"✧"}];
 const collection=selectedCollection?collections.find(c=>c.id===selectedCollection):null;const collectionPosts=collection?posts.filter(p=>collection.postIds.includes(p.id)):[];
 return <div className="app-shell"><header className="topbar"><button className="brand brand-button" onClick={goHome}>ximo<span>.</span></button><button className="profile-button" onClick={openProfile}>S</button></header><main>
 {view==="collection"&&collection?<section className="collection-page"><button className="back-link" onClick={openSaved}>← Saved ideas</button><div className="collection-hero"><div className="collection-cover">{collectionPosts[0]?<img src={collectionPosts[0].image} alt=""/>:<div>✦</div>}</div><div><p className="eyebrow">COLLECTION</p><h1>{collection.name}</h1>{collection.description&&<p className="hero-copy">{collection.description}</p>}<span className="collection-count">{collectionPosts.length} {collectionPosts.length===1?"idea":"ideas"}</span></div><div className="collection-actions"><button onClick={()=>editCollection(collection)}>Edit</button><button onClick={()=>deleteCollection(collection.id)}>Delete</button></div></div>{renderFeed(collectionPosts,"masonry")}</section>
 :view==="profile"?<section className="profile-page"><div className="profile-hero"><div className="profile-avatar">S</div><div className="profile-info"><p className="eyebrow">XIMO CREATOR</p><h1>Storybound</h1><p>Ideas I want to make real.</p></div></div><div className="profile-stats"><div><strong>{profilePosts.length}</strong><span>Posts</span></div><div><strong>{savedPosts.length}</strong><span>Saved</span></div><div><strong>{new Set(profilePosts.map(p=>p.category)).size}</strong><span>Topics</span></div></div><div className="account-profile-actions"><button className="primary" onClick={openCategoryManager}>✦ Manage Categories</button><button className="primary" onClick={openSaved}>▣ Collections</button><button onClick={()=>window.ximoLogout?.()}>Log out</button></div><div className="profile-tabs"><button className={profileTab==="posts"?"active":""} onClick={()=>setProfileTab("posts")}>My Posts</button><button className={profileTab==="saved"?"active":""} onClick={()=>setProfileTab("saved")}>Saved Ideas</button></div><div className="profile-heading"><h2>{profileTab==="posts"?"My posts":"Saved ideas"}</h2><span>{profileTab==="posts"?profilePosts.length:savedPosts.length} ideas</span></div>{renderFeed(profileTab==="posts"?profilePosts:savedPosts)}</section>
 :view==="saved"?<section className="saved-page"><div className="feed-section-heading"><div><p className="eyebrow">YOUR COLLECTIONS</p><h1>Saved ideas.</h1><p className="hero-copy">Keep your inspiration organized into collections.</p></div><button className="primary collection-create-button" onClick={()=>{setEditingCollection(null);setCollectionName("");setCollectionDescription("");setShowCollectionCreate(true)}}>+ New collection</button></div>{collections.length>0&&<div className="collections-grid">{collections.map(c=>{const cp=posts.filter(p=>c.postIds.includes(p.id));return <article className="collection-card" key={c.id} onClick={()=>openCollection(c.id)}><div className="collection-card-cover">{cp[0]?<img src={cp[0].image} alt=""/>:<div className="collection-empty-cover">✦</div>}<span>{cp.length}</span></div><div className="collection-card-body"><div><h2>{c.name}</h2>{c.description&&<p>{c.description}</p>}</div><button onClick={e=>{e.stopPropagation();editCollection(c)}}>•••</button></div></article>})}</div>}<div className="saved-divider"><span>All saved ideas</span><strong>{savedPosts.length}</strong></div>{renderFeed(savedPosts,"masonry")}</section>
 :view==="search"?<section className="search-page"><div className="search-page-head"><p className="eyebrow">DISCOVER ON XIMO</p><h1>Find your next<br/><span>great idea.</span></h1><form className="search-box search-page-box" onSubmit={submitSearch}><span>⌕</span><input className="search-page-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search rooms, setups, styles..." autoComplete="off"/>{query&&<button type="button" onClick={()=>setQuery("")}>×</button>}</form>{query?<p className="search-result-label">{filtered.length} {filtered.length===1?"idea":"ideas"} for <strong>“{query}”</strong></p>:<p className="search-result-label">Explore ideas by category or start typing above.</p>}</div>{!query&&recentSearches.length>0&&<div className="recent-searches"><div className="discovery-heading"><h2>Recent searches</h2><button className="recent-clear" onClick={clearRecentSearches}>Clear all</button></div><div className="recent-search-chips">{recentSearches.map(x=><button key={x} onClick={()=>useRecentSearch(x)}>{x}<span onClick={e=>{e.stopPropagation();removeRecentSearch(x)}}>×</span></button>)}</div></div>}{renderFeed(filtered,"masonry")}</section>
 :<section className="home-page"><div className="hero"><div><p className="eyebrow">WELCOME BACK</p><h1>Ideas worth<br/><span>keeping.</span></h1><p className="hero-copy">A personal space for things you want to make real.</p></div><button className="hero-create" onClick={()=>setShowCreate(true)}>+ Create idea</button></div><div className="category-strip"><button className={active==="Home"?"active":""} onClick={()=>chooseCategory("Home")}>⌂ <span>Home</span></button>{categories.filter(c=>c!=="Home").map((c,i)=><button key={c} className={active===c?"active":""} onClick={()=>chooseCategory(c)}>{iconForCategory(c,i)} <span>{c}</span></button>)}<button onClick={openCategoryManager}>＋ <span>Manage</span></button></div><div className="feed-toolbar"><div className="feed-tabs">{feedTabs.map(t=><button key={t.id} className={feedMode===t.id?"active":""} onClick={()=>{setFeedMode(t.id);setFeedCount(1)}}>{t.icon} {t.label}</button>)}</div><button className="search-trigger" onClick={openSearch}>⌕ Search</button></div>{active!=="Home"&&<div className="active-category-banner"><span>{iconForCategory(active)}</span><div><p className="eyebrow">CATEGORY</p><h2>{active}</h2><p>{posts.filter(p=>p.category===active).length} ideas</p></div></div>}{loading?<div className="loading-grid">{[1,2,3,4,5,6].map(i=><div className="skeleton" key={i}/>)}</div>:renderFeed(active!=="Home"?filtered:shownFeed,"masonry")}{active==="Home"&&shownFeed.length<modePosts.length&&<button className="load-more" onClick={loadMore}>Load more ideas</button>}</section>}
 </main>
 {showCreate&&<div className="modal-backdrop" onClick={()=>setShowCreate(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NEW IDEA</p><h2>Create something.</h2></div><button onClick={()=>setShowCreate(false)}>×</button></div><form onSubmit={publish}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give your idea a name"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Image<input type="file" accept="image/*" onChange={handleImage}/></label>{image&&<img className="upload-preview" src={image} alt="Preview"/>}<button className="primary publish-button" type="submit">Publish idea</button></form></div></div>}
 {showCollectionCreate&&<div className="modal-backdrop" onClick={()=>setShowCollectionCreate(false)}><div className="modal collection-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">{editingCollection?"EDIT COLLECTION":"NEW COLLECTION"}</p><h2>{editingCollection?"Make it yours.":"Collect the good stuff."}</h2></div><button onClick={()=>setShowCollectionCreate(false)}>×</button></div><label>Name<input value={collectionName} onChange={e=>setCollectionName(e.target.value)} placeholder="e.g. Dream workspace" autoFocus/></label><label>Description <span className="optional">optional</span><textarea value={collectionDescription} onChange={e=>setCollectionDescription(e.target.value)} placeholder="What belongs in this collection?" rows="3"/></label><button className="primary publish-button" onClick={createCollection}>{editingCollection?"Save changes":"Create collection"}</button></div></div>}
 {showCategories&&<div className="modal-backdrop" onClick={()=>setShowCategories(false)}><div className="modal categories-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">YOUR TOPICS</p><h2>Categories.</h2></div><button onClick={()=>setShowCategories(false)}>×</button></div><div className="category-manager-form"><input value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder={editingCategory?"Rename category":"New category"}/><button className="primary" onClick={saveCategory}>{editingCategory?"Save":"Add"}</button></div><div className="category-manager-list">{customOnly.length===0?<p className="manager-empty">No custom categories yet. Create one above.</p>:customOnly.map(c=><div key={c}><span>{iconForCategory(c)} {c}</span><div><button onClick={()=>startEditCategory(c)}>Edit</button><button onClick={()=>deleteCategory(c)}>Delete</button></div></div>)}</div></div></div>}
 {selectedPost&&<div className="modal-backdrop post-detail-backdrop" onClick={()=>setSelectedPost(null)}><div className="post-detail" onClick={e=>e.stopPropagation()}><button className="detail-close" onClick={()=>setSelectedPost(null)}>×</button><img src={selectedPost.image} alt={selectedPost.title}/><div className="detail-body"><span className="detail-category">{selectedPost.category}</span><h1>{selectedPost.title}</h1><div className="detail-actions"><button className={saved.includes(selectedPost.id)?"primary":""} onClick={()=>toggleSave(selectedPost.id)}>{saved.includes(selectedPost.id)?"♥ Saved":"♡ Save"}</button><button onClick={()=>sharePost(selectedPost)}>↗ Share</button></div>{collections.length>0&&<div className="add-to-collection"><p className="eyebrow">ADD TO COLLECTION</p><div>{collections.map(c=><button key={c.id} className={c.postIds.includes(selectedPost.id)?"collection-chip active":"collection-chip"} onClick={()=>toggleCollectionPost(c.id,selectedPost.id)}>{c.postIds.includes(selectedPost.id)?"✓":"+"} {c.name}</button>)}</div></div>}{relatedPosts.length>0&&<div className="related"><p className="eyebrow">MORE LIKE THIS</p>{relatedPosts.map(p=><button key={p.id} onClick={()=>setSelectedPost(p)}><img src={p.image} alt=""/><span>{p.title}</span></button>)}</div>}</div></div></div>}
 {toast&&<div className="toast">{toast}</div>}<nav className={`bottom-nav ${navHidden?"nav-hidden":""}`}><button onClick={goHome} className={view==="home"?"active":""}>⌂<span>Home</span></button><button onClick={openSearch} className={view==="search"?"active":""}>⌕<span>Search</span></button><button className="nav-create" onClick={()=>setShowCreate(true)}>+</button><button onClick={openSaved} className={view==="saved"||view==="collection"?"active":""}>♡<span>Saved</span></button><button onClick={openProfile} className={view==="profile"?"active":""}>◉<span>Profile</span></button></nav>
 </div>}
ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
