import React, { useEffect, useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import "./style.css";
import "./profile.css";

const seedPosts=[
{id:1,title:"Warm minimal living room",category:"Home",height:"tall",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85",score:98},
{id:2,title:"A cozy reading corner",category:"Cozy",height:"short",image:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85",score:91},
{id:3,title:"Simple desk setup",category:"Workspace",height:"medium",image:"https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=900&q=85",score:95},
{id:4,title:"Soft bedroom ideas",category:"Bedroom",height:"tall",image:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=85",score:94},
{id:5,title:"Plants that change a room",category:"Plants",height:"medium",image:"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85",score:88},
{id:6,title:"Clean kitchen inspiration",category:"Kitchen",height:"short",image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85",score:92}
];
const categories=["Home","Cozy","Workspace","Bedroom","Plants","Kitchen"];
const discoveryCategories=[{name:"Home",icon:"⌂"},{name:"Cozy",icon:"☁"},{name:"Workspace",icon:"▣"},{name:"Bedroom",icon:"◒"},{name:"Plants",icon:"✿"},{name:"Kitchen",icon:"◇"}];
function App(){
const[active,setActive]=useState("Home"),[view,setView]=useState("home"),[profileTab,setProfileTab]=useState("posts"),[query,setQuery]=useState(""),[selectedPost,setSelectedPost]=useState(null),[saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem("ximo-saved")||"[]")),[userPosts,setUserPosts]=useState(()=>JSON.parse(localStorage.getItem("ximo-posts")||"[]")),[showCreate,setShowCreate]=useState(false),[title,setTitle]=useState(""),[category,setCategory]=useState("Home"),[image,setImage]=useState(""),[imageName,setImageName]=useState(""),[navHidden,setNavHidden]=useState(false),[feedMode,setFeedMode]=useState("for-you"),[feedCount,setFeedCount]=useState(1),[loading,setLoading]=useState(true),[toast,setToast]=useState("");
useEffect(()=>localStorage.setItem("ximo-saved",JSON.stringify(saved)),[saved]);useEffect(()=>localStorage.setItem("ximo-posts",JSON.stringify(userPosts)),[userPosts]);
useEffect(()=>{const t=setTimeout(()=>setLoading(false),650);return()=>clearTimeout(t)},[]);
useEffect(()=>{let lastY=window.scrollY;const onScroll=()=>{const y=window.scrollY;if(y>lastY+8&&y>100)setNavHidden(true);if(y<lastY-8)setNavHidden(false);lastY=y};window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
useEffect(()=>{document.body.style.overflow=selectedPost?"hidden":"";return()=>{document.body.style.overflow=""}},[selectedPost]);
useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(t)},[toast]);
const posts=useMemo(()=>[...userPosts,...seedPosts],[userPosts]);
useEffect(()=>{const id=new URLSearchParams(window.location.search).get("post");if(!id)return;const match=posts.find(p=>String(p.id)===id);if(match){setSelectedPost(match);setNavHidden(false)}},[posts]);
const filtered=useMemo(()=>posts.filter(p=>{const q=query.trim().toLowerCase();return(!q||`${p.title} ${p.category}`.toLowerCase().includes(q))&&(active==="Home"||active==="Saved"||active==="Search"||active==="Profile"||p.category===active)&&(active!=="Saved"||saved.includes(p.id))}),[posts,query,active,saved]);
const forYou=useMemo(()=>[...posts].sort((a,b)=>{const as=saved.includes(a.id)?20:0,bs=saved.includes(b.id)?20:0;return(bs+b.score)-(as+a.score)}),[posts,saved]);
const trending=useMemo(()=>[...posts].sort((a,b)=>b.score-a.score),[posts]);
const fresh=useMemo(()=>[...posts].reverse(),[posts]);
const modePosts=feedMode==="trending"?trending:feedMode==="fresh"?fresh:forYou;
const shownFeed=modePosts.slice(0,feedCount*4);
const goHome=()=>{setView("home");setActive("Home");setQuery("");setFeedMode("for-you");setFeedCount(1);window.scrollTo({top:0,behavior:"smooth"})};
const openSearch=()=>{setView("search");setActive("Search");setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"});setTimeout(()=>document.querySelector(".search-page-input")?.focus(),120)};
const chooseCategory=item=>{setQuery("");setActive(item);setView("home");setFeedMode("for-you");setFeedCount(1);setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};
const openProfile=()=>{setView("profile");setActive("Profile");setProfileTab("posts");setNavHidden(false);window.scrollTo({top:0,behavior:"smooth"})};
const openPost=p=>{setSelectedPost(p);setNavHidden(false)};
const toggleSave=id=>{const willSave=!saved.includes(id);setSaved(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);setToast(willSave?"Saved to your Ximo ideas 🧡":"Removed from saved")};
const sharePost=async p=>{const url=`${window.location.origin}${window.location.pathname}?post=${encodeURIComponent(p.id)}`;try{if(navigator.share){await navigator.share({title:`${p.title} — Ximo`,text:`Check out this idea on Ximo: ${p.title}`,url});setToast("Shared from Ximo 🧡");return}await navigator.clipboard.writeText(url);setToast("Post link copied 🧡")}catch(e){if(e?.name!=="AbortError"){try{await navigator.clipboard.writeText(url);setToast("Post link copied 🧡")}catch{setToast("Could not share this post")}}}};
const handleImage=e=>{const file=e.target.files?.[0];if(!file||!file.type.startsWith("image/"))return;setImageName(file.name);const reader=new FileReader();reader.onload=()=>setImage(reader.result);reader.readAsDataURL(file)};
const publish=e=>{e.preventDefault();if(!title.trim()||!image)return;setUserPosts(cur=>[{id:`local-${Date.now()}`,title:title.trim(),category,height:"medium",image,score:100},...cur]);setTitle("");setCategory("Home");setImage("");setImageName("");setShowCreate(false);setToast("Your idea is live on Ximo 🧡");goHome()};
const loadMore=()=>{if(shownFeed.length<modePosts.length){setFeedCount(c=>c+1);setToast("More ideas loaded")}};
const renderFeed=(items=filtered,mode="normal")=>items.length===0?<div className="empty-state"><div className="empty-icon">⌕</div><h2>No ideas found.</h2><p>Try a different search or explore another category.</p><button onClick={()=>{setQuery("");setActive("Search")}}>Clear search</button></div>:<section className={`feed ${mode==="masonry"?"masonry-feed":""}`}>{items.map(p=><article className={`card ${p.height}`} key={p.id} onClick={()=>openPost(p)} tabIndex="0" onKeyDown={e=>e.key==="Enter"&&openPost(p)}><img src={p.image} alt={p.title} loading="lazy"/><div className="card-overlay"><div><span>{p.category}</span><h2>{p.title}</h2></div><button className={saved.includes(p.id)?"save saved":"save"} onClick={e=>{e.stopPropagation();toggleSave(p.id)}}>{saved.includes(p.id)?"♥":"♡"}</button></div></article>)}</section>;
const savedPosts=posts.filter(p=>saved.includes(p.id)),profilePosts=userPosts,relatedPosts=selectedPost?posts.filter(p=>p.id!==selectedPost.id&&p.category===selectedPost.category).slice(0,4):[];
const feedTabs=[{id:"for-you",label:"For You",icon:"✦"},{id:"trending",label:"Trending",icon:"↗"},{id:"fresh",label:"Fresh",icon:"✧"}];
return <div className="app-shell"><header className="topbar"><button className="brand brand-button" onClick={goHome}>ximo<span>.</span></button><button className="profile-button" onClick={openProfile}>S</button></header><main>
{view==="profile"?<section className="profile-page"><div className="profile-hero"><div className="profile-avatar">S</div><div className="profile-info"><p className="eyebrow">XIMO CREATOR</p><h1>Storybound</h1><p>Ideas I want to make real.</p></div></div><div className="profile-stats"><div><strong>{profilePosts.length}</strong><span>Posts</span></div><div><strong>{savedPosts.length}</strong><span>Saved</span></div><div><strong>{new Set(profilePosts.map(p=>p.category)).size}</strong><span>Topics</span></div></div><div className="profile-tabs"><button className={profileTab==="posts"?"active":""} onClick={()=>setProfileTab("posts")}>My Posts</button><button className={profileTab==="saved"?"active":""} onClick={()=>setProfileTab("saved")}>Saved Ideas</button></div><div className="profile-heading"><h2>{profileTab==="posts"?"My posts":"Saved ideas"}</h2><span>{profileTab==="posts"?profilePosts.length:savedPosts.length} ideas</span></div>{renderFeed(profileTab==="posts"?profilePosts:savedPosts)}</section>
:view==="search"?<section className="search-page"><div className="search-page-head"><p className="eyebrow">DISCOVER ON XIMO</p><h1>Find your next<br/><span>great idea.</span></h1><div className="search-box search-page-box"><span>⌕</span><input className="search-page-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search rooms, setups, styles..." autoComplete="off"/>{query&&<button onClick={()=>setQuery("")}>×</button>}</div>{query?<p className="search-result-label">{filtered.length} {filtered.length===1?"idea":"ideas"} for <strong>“{query}”</strong></p>:<p className="search-result-label">Explore ideas by category or start typing above.</p>}</div>{!query&&<><div className="discovery-heading"><h2>Explore categories</h2><span>Pick a vibe</span></div><div className="discovery-grid">{discoveryCategories.map(i=><button key={i.name} className="discovery-card" onClick={()=>chooseCategory(i.name)}><span>{i.icon}</span><strong>{i.name}</strong><small>{posts.filter(p=>p.category===i.name).length} ideas</small></button>)}</div><div className="discovery-heading"><h2>Popular ideas</h2><span>Fresh inspiration</span></div></>}{renderFeed(query?filtered:forYou,"masonry")}</section>
:<><section className="hero"><p className="eyebrow">YOUR SPACE. YOUR IDEAS.</p><h1>Make your space<br/><span>feel like you.</span></h1><p className="hero-copy">Discover rooms, setups, styles and little ideas worth saving.</p><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={openSearch} placeholder="Search ideas..."/></div></section><div className="feed-switcher">{feedTabs.map(t=><button key={t.id} className={feedMode===t.id?"feed-tab active":"feed-tab"} onClick={()=>{setFeedMode(t.id);setFeedCount(1);window.scrollTo({top:0,behavior:"smooth"})}}><span>{t.icon}</span>{t.label}</button>)}</div><div className="category-row">{["Home",...categories].filter((x,i,a)=>a.indexOf(x)===i).map(i=><button key={i} className={active===i?"category active":"category"} onClick={()=>chooseCategory(i)}>{i}</button>)}</div><div className="feed-section-heading"><div><p className="eyebrow">{feedMode==="for-you"?"CURATED FOR YOU":feedMode==="trending"?"RIGHT NOW":"JUST ADDED"}</p><h2>{feedMode==="for-you"?"Made for your taste.":feedMode==="trending"?"What people are loving.":"Fresh ideas, just in."}</h2></div><span>{shownFeed.length} ideas</span></div>{loading?<div className="skeleton-feed">{[1,2,3,4,5,6].map(i=><div className="skeleton skeleton-card" key={i}/>)}</div>:renderFeed(shownFeed,"masonry")}{shownFeed.length<modePosts.length&&<div className="load-more-wrap"><button className="load-more" onClick={loadMore}>Show me more <span>↓</span></button></div>}<div className="category-spotlight"><div className="feed-section-heading"><div><p className="eyebrow">EXPLORE MORE</p><h2>Find your next vibe.</h2></div></div><div className="discovery-grid">{discoveryCategories.slice(0,6).map(i=><button key={i.name} className="discovery-card" onClick={()=>chooseCategory(i.name)}><span>{i.icon}</span><strong>{i.name}</strong><small>{posts.filter(p=>p.category===i.name).length} ideas</small></button>)}</div></div></>}</main>
{selectedPost&&<div className="post-detail" role="dialog" aria-modal="true"><button className="detail-close" onClick={()=>{setSelectedPost(null);if(window.location.search)window.history.replaceState({},"",window.location.pathname)}}>×</button><div className="detail-image-wrap"><img className="detail-image" src={selectedPost.image} alt={selectedPost.title}/></div><div className="detail-content"><div className="detail-meta"><span>{selectedPost.category}</span><div style={{display:"flex",gap:8,alignItems:"center"}}><button className={saved.includes(selectedPost.id)?"detail-save saved":"detail-save"} onClick={()=>toggleSave(selectedPost.id)}>{saved.includes(selectedPost.id)?"♥ Saved":"♡ Save"}</button><button onClick={()=>sharePost(selectedPost)} style={{minHeight:42,padding:"0 17px",cursor:"pointer",border:"1px solid #e5e5e5",borderRadius:999,background:"#171717",color:"#fff",fontSize:13,fontWeight:800}}>↗ Share</button></div></div><h1>{selectedPost.title}</h1><p>Save this idea to your Ximo collection or share it with someone who needs the inspiration.</p>{relatedPosts.length>0&&<div className="related-section"><div className="discovery-heading"><h2>More like this</h2><span>{selectedPost.category}</span></div><div className="related-grid">{relatedPosts.map(p=><button className="related-card" key={p.id} onClick={()=>openPost(p)}><img src={p.image} alt={p.title}/><span>{p.title}</span></button>)}</div></div>}</div></div>}
{showCreate&&<div className="create-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShowCreate(false)}><form className="create-panel" onSubmit={publish}><div className="create-header"><div><p className="eyebrow">SHARE AN IDEA</p><h2>Create on Ximo</h2></div><button type="button" className="close-button" onClick={()=>setShowCreate(false)}>×</button></div><label className={`upload-box ${image?"has-image":""}`}>{image?<img src={image} alt="Preview"/>:<><strong>+</strong><span>Choose an image</span><small>PNG, JPG or WEBP</small></>}<input type="file" accept="image/*" onChange={handleImage}/></label>{imageName&&<p className="file-name">{imageName}</p>}<label className="field-label">Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give your idea a name..." maxLength={80}/></label><label className="field-label">Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(i=><option key={i}>{i}</option>)}</select></label><button className="publish-button" type="submit" disabled={!title.trim()||!image}>Publish idea</button></form></div>}
{toast&&<div className="toast"><span>●</span> {toast}</div>}<nav className={`bottom-nav ${navHidden?"nav-hidden":""}`}><button className={active==="Home"&&view==="home"?"nav-item active":"nav-item"} onClick={goHome}><span>⌂</span><small>Home</small></button><button className={active==="Search"?"nav-item active":"nav-item"} onClick={openSearch}><span>⌕</span><small>Search</small></button><button className="create-button" onClick={()=>{setNavHidden(false);setShowCreate(true)}}>+</button><button className={active==="Saved"?"nav-item active":"nav-item"} onClick={()=>{setView("home");setActive("Saved");setQuery("");setFeedCount(1);window.scrollTo({top:0,behavior:"smooth"})}}><span>♡</span><small>Saved</small></button><button className={active==="Profile"?"nav-item active":"nav-item"} onClick={openProfile}><span>◯</span><small>Profile</small></button></nav></div>}
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
